{
	"schema_version": "1.6.0",
	"id": "RLSA-2024:3275",
	"modified": "2024-06-14T14:02:17.482295Z",
	"published": "2024-06-14T13:59:16.809606Z",
	"related": [
		"CVE-2023-29483"
	],
	"summary": "Moderate: python-dns security update",
	"details": "The python-dns package contains the dnslib module that implements a DNS client and additional modules that define certain symbolic constants used by DNS, such as dnstype, dnsclass and dnsopcode.\n\nSecurity Fix(es):\n\n* dnspython: denial of service in stub resolver (CVE-2023-29483)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
	"affected": [
		{
			"package": {
				"ecosystem": "Rocky Linux:8",
				"name": "python-dns",
				"purl": "pkg:rpm/rocky-linux/python-dns?distro=rocky-linux-8-x86-64&epoch=0"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.15.0-12.el8_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/resf-osv-data/RLSA-2024:3275.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://errata.rockylinux.org/RLSA-2024:3275"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274520"
		}
	],
	"credits": [
		{
			"name": "Rocky Enterprise Software Foundation"
		},
		{
			"name": "Red Hat"
		}
	]
}
